################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
DSP2833x_Libraries/DSP2833x_ADC_cal.obj: ../DSP2833x_Libraries/DSP2833x_ADC_cal.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_ADC_cal.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_Adc.obj: ../DSP2833x_Libraries/DSP2833x_Adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_Adc.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_CodeStartBranch.obj: ../DSP2833x_Libraries/DSP2833x_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_CodeStartBranch.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_CpuTimers.obj: ../DSP2833x_Libraries/DSP2833x_CpuTimers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_CpuTimers.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_DefaultIsr.obj: ../DSP2833x_Libraries/DSP2833x_DefaultIsr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_DefaultIsr.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_EPwm.obj: ../DSP2833x_Libraries/DSP2833x_EPwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_EPwm.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_GlobalVariableDefs.obj: ../DSP2833x_Libraries/DSP2833x_GlobalVariableDefs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_GlobalVariableDefs.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_Gpio.obj: ../DSP2833x_Libraries/DSP2833x_Gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_Gpio.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_MemCopy.obj: ../DSP2833x_Libraries/DSP2833x_MemCopy.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_MemCopy.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_PieCtrl.obj: ../DSP2833x_Libraries/DSP2833x_PieCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_PieCtrl.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_PieVect.obj: ../DSP2833x_Libraries/DSP2833x_PieVect.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_PieVect.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_Sci.obj: ../DSP2833x_Libraries/DSP2833x_Sci.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_Sci.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_Spi.obj: ../DSP2833x_Libraries/DSP2833x_Spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_Spi.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_SysCtrl.obj: ../DSP2833x_Libraries/DSP2833x_SysCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_SysCtrl.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

DSP2833x_Libraries/DSP2833x_usDelay.obj: ../DSP2833x_Libraries/DSP2833x_usDelay.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/IICOLED" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/dc_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/Public" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/epwm" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_common/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/Debug/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/DSP2833x_Libraries" --include_path="E:/DSP8233x_ProjectExample/DSP2833x_Libraries/DSP2833x_headers/include" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/beep" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/exti" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/key" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd1602" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/lcd9648" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/leds" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/relay" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/smg" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/step_motor" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/time" --include_path="E:/DSP8233x_ProjectExample/work/smart fans/APP/uart" --include_path="E:/software/ti/ccsv6/tools/compiler/c2000_15.12.3.LTS/include" -g --display_error_number --diag_warning=225 --diag_wrap=off --preproc_with_compile --preproc_dependency="DSP2833x_Libraries/DSP2833x_usDelay.d" --obj_directory="DSP2833x_Libraries" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


